fix: error messages when ID don't exist
luanarahal/nestjs-crud pull request #8
Opened 2023-05-25 22:36 UTC by luanarahal

I fixed error messages when:
- we try find a ID that don't exist
- we try update a ID that don't exist

2023-05-26 12:20 UTC, antoniomatiolijr requested changes

2023-05-26 12:20 UTC, antoniomatiolijr commented on src/controller/todo.controller.ts
> +      res.status(HttpStatus.INTERNAL_SERVER_ERROR)
Não é um `HttpStatus.INTERNAL_SERVER_ERROR` procura no HTTP um erro que melhor representa quando um recurso não existe.

2023-05-26 12:20 UTC, antoniomatiolijr commented on src/controller/todo.controller.ts
> +      res.status(HttpStatus.INTERNAL_SERVER_ERROR)
Não é um HttpStatus.INTERNAL_SERVER_ERROR procura no HTTP um erro que melhor representa quando um recurso não existe.

2023-05-26 12:20 UTC, antoniomatiolijr commented on src/controller/todo.controller.ts
> +      return item;
Aqui vc pode usar a mesma tese do erro `res.status.json` só que com sucesso.

2023-05-26 12:20 UTC, antoniomatiolijr commented on src/controller/todo.controller.ts
> +  async findAll(@Res({ passthrough: true }) res: Response) {
pra que vc precisa desse `{ passthrough: true }`?

2023-05-26 12:20 UTC, antoniomatiolijr commented on src/controller/todo.controller.ts
> +      return items;
E vc pode retornar um array vazio se não encontrar nada não tem problema. Pois seu método está querendo retornar todos e não somente um caso especifico como o update, delete e o findOne.

2023-05-26 12:20 UTC, antoniomatiolijr commented on src/controller/todo.controller.ts
> +      return `Registro com a ID ${id} não encontrado.`;
Aqui também está faltando a mensagem de erro com o HTTP Status adequado.

2023-05-26 13:30 UTC, luanarahal commented on src/controller/todo.controller.ts
> +  async findAll(@Res({ passthrough: true }) res: Response) {
Eu coloquei o { passthrough: true } porque ele permite que eu acesse o objeto fora de escopo na função assíncrona, se eu tiro ele, ele não consegue acessar, dai o postman fica procurando e não acha nada

2023-05-26 13:30 UTC, luanarahal commented on src/controller/todo.controller.ts
> +      return item;
coloquei no delete e no update para retornar com a mensagem de sucesso, mas se eu coloco no findOne e findAll ele retorna só a mensagem, ai deixei como tava, td bem?

2023-05-26 19:47 UTC, antoniomatiolijr requested changes
Tira todos os return e substitui por `res.status.json`

2023-05-26 19:47 UTC, antoniomatiolijr commented on src/controller/todo.controller.ts
> +      return item;
Não ta tudo bem kkkkkk

2023-05-26 20:26 UTC, luanarahal commented on src/controller/todo.controller.ts
> +      return item;
ah ta kkkkk

2023-05-26 20:26 UTC, luanarahal commented on src/controller/todo.controller.ts
> +  async findAll(@Res({ passthrough: true }) res: Response) {
tirei

2023-05-29 14:31 UTC, antoniomatiolijr requested changes

2023-05-29 14:31 UTC, antoniomatiolijr commented on src/controller/todo.controller.ts
> +      res.status(HttpStatus.BAD_REQUEST).json({ message: 'Erro ao criar registro.'});
Aqui não é um BAD REQUEST. 

Você usa bad request, sempre quando a requisição não está aderente ao que o código pede, exemplo:

Precisa enviar o nome e vc envia em branco, vc retorna então para um usuário dizendo que aquele campo deve ser preenchido.

Como nesse caso ainda não vamos tratar os erros no detalhe pode retornar um `500` por hora.

2023-05-29 17:53 UTC, antoniomatiolijr approved these changes

2023-05-29 17:53 UTC, merged